### ISSUE TITLE
Enable UTF characters for rule parsing

### ISSUE THREAD

**Issue by ZA0068** [aresio/simpful#11]
Hi, is there a way to parse an utf-8, -16 and even -32 characters to the rule base?

such as greek letter θ, is it possible?

if not, when will it be implimented?

**Comment by sspola** [comment]
Hi @ZA0068 

thank you again for your interest in simpful!

The last commit (1b4411894a18995f7fc710bf76bc4b30bcb3d5e1) contains a small fix that enables to parse unicode characters (which are supported by default in python `re`).
