### ISSUE TITLE
simpful >=2.9.0 is not compatible with python <3.8

### ISSUE THREAD

**Issue by DManowitz** [aresio/simpful#18]
This package claims compatibility with Python 3.7.  However, in simpful.py (since version 2.9.0), it imports prod from math, which was only introduced in Python 3.8.

**Comment by sspola** [comment]
Hi @DManowitz 
the 3.7 classifier in the setup.py was not updated after simpful 2.9 release.
I updated the classifiers in 0e59175.

The support for Python 3.7 will end soon, so we opted for >=3.8 compatibility.
