### ISSUE TITLE
How can I plot the output surface?

### ISSUE THREAD

**Issue by khinggan** [aresio/simpful#25]
Thanks for the excellent repo and paper. 

I want to plot the output surface like Fig.4 in the [paper](https://www.atlantis-press.com/journals/ijcis/125945415/view). 

What kind of code should I add in the [mamdani tip problem example](https://github.com/aresio/simpful/blob/master/examples/example_tip_mamdani.py) to get the figure like Fig. 4. in the paper?

Thanks

**Comment by sspola** [comment]
Hi @khinggan and thank you! 😃 
In the examples folder there is a code snippet that should do exactly what you are looking for.
You can find it [here](https://github.com/aresio/simpful/blob/master/examples/example_output_surface.py).

Hope it helps!

**Comment by sspola** [comment]
@aresio just made me notice that we also have a function to do that [`plot_surface`](https://github.com/aresio/simpful/blob/785d7c5721d289d61c1991c6cfb22add22d304d9/simpful/simpful.py#L907C53-L907C53).
It's a method of the FuzzySystem object

**Comment by khinggan** [comment]
Thanks for @sspola kind reply, it helps me a lot.

best regards
