### ISSUE TITLE
is there any way to Save The Fuzzy Rules in FCL format in a file ? 

### ISSUE THREAD

**Issue by mojtabatorabii** [aresio/simpful#6]
is there any way to Save The Fuzzy Rules in FCL format in a file ?

**Comment by aresio** [comment]
Dear Mojtaba,
thank you for your interest in Simpful. 
We are not planning the export of Simpful models to the FCL format. We are working on the support of FML in future releases. 
Please note that Simpful accepts fuzzy rules that are defined using strings; in the case of 0-order Sugeno or Mamdani systems, you could re-use those strings to export the rules to a FCL file.

All the best,
Marco
