### ISSUE TITLE
Surpressing the division by 0 warning via extra parameter (maybe verbose?)

### ISSUE THREAD

**Issue by MtthVt** [aresio/simpful#9]
Atm, if the sum of rules firing is 0, division by 0 is captured and just 0 is returned. This behaviour is expected and doesn't lead to any error. However, everytime this event occurs, a warning is printed [see here](https://github.com/aresio/simpful/blob/f90c8b2220523bbdf45430f601b9d31791a55da6/simpful/simpful.py#L556).
Especially for systems designed to lead to 0 values in specific cases, this can produce a large output. It is desired that this warning could be surpressed by a specific setting or maybe even with the "verbose" parameter.

**Comment by aresio** [comment]
Thank you for your suggestion, we are implementing the verbosity argument for the inference method that you proposed. We will post here as soon as it is complete.

**Comment by sspola** [comment]
Hi @matthi97 !
I just pushed a [new version](80cca80146b02a14f33e50e6d8a0042e4bda3388), with an optional `ignore_warnings` boolean argument for the inference methods.

I hope this solves the issue!

**Comment by MtthVt** [comment]
Happy new year @sspola !
Thank you very much for including the parameter. I tested the new version with my code and it works.
Can you trigger the pipeline to build a new pip package?

**Comment by sspola** [comment]
happy new year to you too!
I'm glad to know that everything is working as it should, thank you for testing.

I just tagged the new version, it should be out on PyPI as well :)
